export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE';

export const USER_SIGN_IN_REQUEST = 'USER_SIGN_IN_REQUEST';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE';

export const USER_SIGN_OUT_REQUEST = 'USER_SIGN_OUT_REQUEST';
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';
export const USER_SIGN_OUT_FAILURE = 'USER_SIGN_OUT_FAILURE';





export const FETCH_RESTAURANT_REQUEST = 'FETCH_RESTAURANT_REQUEST';
export const FETCH_RESTAURANT_SUCCESS = 'FETCH_RESTAURANT_SUCCESS';
export const FETCH_RESTAURANT_FAILURE = 'FETCH_RESTAURANT_FAILURE';

export const ADD_RESTAURANT_REQUEST = 'ADD_RESTAURANT_REQUEST';
export const ADD_RESTAURANT_SUCCESS = 'ADD_RESTAURANT_SUCCESS';
export const ADD_RESTAURANT_FAILURE = 'ADD_RESTAURANT_FAILURE';

export const FETCH_RESTAURANT_LIST_REQUEST = 'FETCH_RESTAURANT_LIST_REQUEST';
export const FETCH_RESTAURANT_LIST_SUCCESS = 'FETCH_RESTAURANT_LIST_SUCCESS';
export const FETCH_RESTAURANT_LIST_FAILURE = 'FETCH_RESTAURANT_LIST_FAILURE';





export const FETCH_MENU_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_MENU_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_MENU_FAILURE = 'FETCH_ITEMS_FAILURE';

export const ADD_MENU_ITEM = 'ADD_ITEM';
export const DELETE_MENU_ITEM = 'DELETE_ITEM';

export const SET_ITEM_FORM_VISIBILITY = 'SET_ITEM_FORM_VISIBILITY';

export const SET_ITEM_MODAL_VISIBILITY = 'SET_ITEM_MODAL_VISIBILITY';

export const SET_RESTAURANT_FORM_VISIBILITY = 'SET_RESTAURANT_FORM_VISIBILITY';


export const ADD_ITEM_TO_ORDER = 'ADD_ITEM_TO_ORDER';
export const ADD_QUANTITY_TO_ORDER = 'ADD_QUANTITY_TO_ORDER';
export const SUBTRACT_QUANTITY_FROM_ORDER = 'SUBTRACT_QUANTITY_FROM_ORDER';
export const REMOVE_ITEM_FROM_ORDER = 'REMOVE_ITEM_FROM_ORDER';

export const SUBMIT_ORDER_REQUEST = 'SUBMIT_ORDER_REQUEST';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';
export const SUBMIT_ORDER_FAILURE = 'SUBMIT_ORDER_FAILURE';


